// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcPjwbuejvrP26sZWgJLKak9DS4Zwr8xQ',
    appId: '1:957717808808:android:58bb100629be44ddf5a49d',
    messagingSenderId: '957717808808',
    projectId: 'flutterhci-ddd47',
    storageBucket: 'flutterhci-ddd47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ZDpfoDHPeKw-x0Yk4LAys0g9Cznp4To',
    appId: '1:957717808808:ios:47c9e82e9f4c1627f5a49d',
    messagingSenderId: '957717808808',
    projectId: 'flutterhci-ddd47',
    storageBucket: 'flutterhci-ddd47.appspot.com',
    iosClientId: '957717808808-pul9j1qplluifhk81il7d903hutvgd8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hci',
  );
}
